device: realsense_d455
frames:
  - color
  - color_optical
  - depth
  - depth_optical
  - infra1
  - infra1_optical
  - infra2
  - infra2_optical
rate_hz: 30.0
width: 1280
height: 720
fovy_deg: 55.0
ideal_depth: true

