robot:
  base: franka_tmr
  spine: franka_spine
  mount: franka_head
  head: franka_head
arms:
  left:
    model: franka_fr3
    prefix: left_
    end_effector: franka_hand
  right:
    model: franka_fr3
    prefix: right_
    end_effector: franka_hand
sensors:
  - model: imu
    mount: imu_mounting_point
  - model: d455
    mounts: [front_mounting_point, rear_mounting_point, left_mounting_point, right_mounting_point]
  - model: nanoscan3
    mounts: [lidar_front_mounting_point, lidar_rear_mounting_point]
  - model: zed_mini
    mount: head_camera_mounting_point
