profile: position
kp:
  tmr: 100.0
  spine: 30000.0
  hand: 200.0
  arm: 500.0
planar_debug:
  - joint: planar_x_joint
    ctrlrange: [-50.0, 50.0]
  - joint: planar_y_joint
    ctrlrange: [-50.0, 50.0]
  - joint: planar_yaw_joint
    ctrlrange: [-6.283185307, 6.283185307]
